package si.inspirited.domain.entityes;


import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import java.util.Random;

@Entity
public class UserEntity {

    @Id
    private String login;

    private String sessName;

    public String autogeneratedLogin() {
        Random rnd = new Random();
        return "user" + rnd.nextInt(777);
    }
    private String recievedLogin;


    public String getLogin() {
        if (login == null) {return autogeneratedLogin();}
        else{return login;}
    }

    public void setLogin(String login) {
        this.login = login;
    }

    public String getSessName() {
        return sessName;
    }

    public void setSessName(String sessName) {
        this.sessName = sessName;
    }



}
